apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theonlineaid/go-api  # Your GitHub repository URL
    targetRevision: main  # The branch you're using (main, for example)
    path: k8s  # Path to your Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc  # Your Kubernetes cluster URL
    namespace: default  # Kubernetes namespace to deploy to
  syncPolicy:
    automated:
      prune: true  # Automatically remove resources if they are removed from the Git repo
      selfHeal: true  # Automatically sync if the current state drifts from the Git state
