apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: onlineaid/go-api:01d717aea494e703c2029464ea3a3fcbb251ab13  # Docker Hub image (make sure to replace with your actual image)
          ports:
            - containerPort: 8080  # Port exposed by your Go API
          env:
            - name: DB_HOST
              value: "db"  # Refers to the db service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "secret"
            - name: DB_NAME
              value: "mydb"
            - name: PORT
              value: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest  # You can change this to a specific version if needed
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_DB
              value: "mydb"
          ports:
            - containerPort: 5432
