apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: onlineaid/go-api:latest  # Docker Hub image (make sure to replace with your actual image)
          ports:
            - containerPort: 8080  # Port exposed by your Go API
